name: outloud
description: A new Flutter project.

version: 0.9.0+2

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  business:
    path: ../business/
  flutter:
    sdk: flutter

  provider: ^4.0.1
  validate: ^1.7.0
  async_redux: ^2.5.2
  provider_for_redux: ^1.1.0
  connectivity: ^0.4.6+2
  timeago: ^2.0.24
  firebase_storage: ^3.1.1
  flutter_i18n: ^0.13.0
  apple_sign_in: ^0.1.0
  device_info: 0.4.2+1

  badges: ^1.1.0
  fluttertoast: ^3.1.3
  flutter_calendar_carousel: ^1.4.10
  flutter_cupertino_date_picker: ^1.0.12
  material_design_icons_flutter: ^3.4.4795
  flutter_speed_dial: ^1.2.5
  flutter_swiper: ^1.1.6
  flutter_slidable: ^0.5.4
  flutter_tags: ^0.4.3
  flutter_typeahead: ^1.7.0
  multi_image_picker: ^4.6.1
  rubber: ^0.4.0
  reorderables: ^0.2.12
  flutter_google_places: ^0.2.3
  expandable: ^4.1.2
  flutter_auth_buttons: ^0.6.0
  enum_to_string: ^1.0.8
  country_code_picker: ^1.2.4
  cached_network_image: ^2.0.0
  google_maps_flutter: ^0.5.24
  path_provider: ^1.6.4
  dotted_border: ^1.0.5
  date_utils: ^0.1.0+3
  gradient_bottom_navigation_bar: ^1.0.0+4
  auto_size_text: ^2.1.0
  flutter_linkify: ^3.1.0
  url_launcher: ^5.4.5
  carousel_slider: ^2.0.0
  keyboard_actions: ^3.2.1
  flutter_screenutil: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/flutter_i18n/
    - images/
  fonts:
    - family: Hiragino
      fonts:
        - asset: fonts/hiragino-maru-gothic-pron-w4.otf
